# Druid 配置
spring:
  profiles:
    active: dev

  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**

  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qg.exclusiveplug.model
  configuration.map-underscore-to-camel-case: true

#Netty 配置
netty:
  tcp-port: 11112
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100

logging:
  file: /root/exclusive_plug/mylog.log
#  pattern:
#    console: "%d - %msg%n"
#    level:
#  config: classpath:logback-spring.xml


#阿里云短信配置
aliyun:
  sms:
    accessKeyId: LTAIAU2HSahyGWkS
    accessKeySecret: OG4kUcuHwjYVuXbP3OBWurSBjb3S5s
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    regionId: cn-hangzhou
    signName: QG智能排插
    dateFormat: yyyy-MM-dd
    endpointName: cn-hangzhou
    templateCode: SMS_148380226

server:
  port: 11111

#  ssl:
#    key-store: classpath:215069416590721.pfx
#    key-store-type: PKCS12
#    key-store-password: 215069416590721
